name: educational_portal3
description: An offline/online app for Class 11 & 12 Computer Science students (User + Admin)
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.8
  flutter_rating_bar: ^4.0.1
  carousel_slider: ^4.2.1

  # PDF Viewer
  pdfx: ^2.6.0

  # File picker
  file_picker: ^8.0.3

  # Path access (documents dir)
  path_provider: ^2.1.4

  # Preferences storage
  shared_preferences: ^2.2.2

  # URL launcher
  url_launcher: ^6.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.png
    - assets/pdfs/class11/
    - assets/pdfs/class12/
    - assets/pdfs/dpp/
